### ISSUE TITLE
Republish 2.0.6

### ISSUE THREAD

**Issue by roarking** [vonnagy/service-container#10]
Akka versions haven't been upgraded on the repository:

http://search.maven.org/remotecontent?filepath=com/github/vonnagy/service-container_2.12/2.0.6/service-container_2.12-2.0.6.pom

Can we republish or bump the project version to 2.0.7?

**Comment by roarking** [comment]
@vonnagy am I missing something?

**Comment by vonnagy** [comment]
@roarking The 2.0.6 version upgraded Akka 2.5.4 along with a few other libraries as well. I am currently working on version 2.0.7 which upgrades to Akka 2.5.7 and Scala 2.12.

Does this satisfy your requirement?

**Comment by roarking** [comment]
yes, it does. I'll wait for version 2.0.7 then. thank you.

**Comment by vonnagy** [comment]
@roarking I release version 2.0.7 today so it should be in place in Maven/Central by EOD or tomorrow. It contains general updates of dependencies and one breaking change, where removed the use of `ActorRefFactory` and replaced with `implicit ExecutionContext` for all uses of the class `RoutedEndpoints`.

```scala
// Old
class ProductEndpoints(implicit system: ActorSystem,
                         actorRefFactory: ActorRefFactory) extends RoutedEndpoints {
}

// New
class ProductEndpoints(implicit system: ActorSystem,
                         executor: ExecutionContext) extends RoutedEndpoints {
}
```

Please, close this issue once you are able to use 2.0.7. Thanks!
