### ISSUE TITLE
404 error on health check

### ISSUE THREAD

**Issue by mf-bmihaescu** [vonnagy/service-container#8]
Hi,
I have a problem with my class path and vonnagy.service-container.

I start a service from init.d where I have class path hard-coded like this :
`JAVA_CP="$lib_dir/com.mf.mfeed-reporting-service-container-1.0.0.jar:$lib_dir/com.github.vonnagy.service-container_2.11-2.0.6.jar:$lib_dir`
When the service starts I execute `curl http://localhost:port/health` and everything works as expected. 

When I try to pass the class path as * 

 `JAVA_CP="${JAVA_CP}:${appDir}/lib/*"`
 `CP_SEP=':'`

The service starts and executes with no problem but when I try the curl command it fails with:
`{"code":404,"message":"The requested resource could not be found but may be available again in the future.","details":"\"The requested resource could not be found\""}`

Could be a problem in the order in witch the libraries are loaded because this is the only thing that differ from those class paths ?

Thanks for your help,
Mihaesu Bogdan

**Comment by vonnagy** [comment]
@mf-bmihaescu Is there any clue in the logs that may show an error when it is either trying to start the service or when accessing the endpoint? I have used something like the following:

```
-cp .:libs/${SERVICE_JAR}:libs/*
```
 The variable `SERVICE_JAR` is your app's jar. You can try without it, but if I remember the `.:` part helped.

**Comment by vonnagy** [comment]
@mf-bmihaescu I did some more testing and found issues if your application uses a reference.conf file and has some akka settings. For the `/health` and `/metrics` endpoints, we use a CIDR filter directive. This directive is dependent on the `akka.http.remote-address-header` setting being turned on. I found that if you have an **akka** section in a reference.conf it will overwrite the required setting. You can add the following in your application.conf to make sure it is set.

```
akka {
  http {
    server {
      # Enables/disables the addition of a `Remote-Address` header
      # holding the clients (remote) IP address.
      remote-address-header = on
    }
  }
}
```
